robotpy/robotpy-installer

robotpy_installer/installer.py
Tested on linux with pip versions
* 7.1.2
* 8.1.2
* 9.0.3
* 10.0.1
Tested on Windows with pip versions
* 9.0.1
* 10.0.1
=> fix download functionality broken by pip10

robotpy_installer/installer.py
- Step in the right direction for #18
=> Try robotpy official packages when downloading from opkg

robotpy_installer/installer.py
=> Store metadata for each file to enable HTTP caching

robotpy_installer/installer.py
=> Be smarter about connecting to a roborio

robotpy_installer/installer.py
=> Check to see if pip3 is installed before using it

robotpy_installer/installer.py
This bug has _really_ gotten on my nerves over the past couple of months.
=> Fix install-pip file check

robotpy_installer/sshcontroller.py
I legitimately cannot deploy without this any more.
Fixes: #36
=> Disable SSH public key authentication

robotpy_installer/sshcontroller.py
Fixes #38, making debugging more possible.
=> Add stderr output

robotpy_installer/sshcontroller.py
Reverts robotpy/robotpy-installer#39
Fixes: #45
=> Revert "Add stderr output"

robotpy_installer/sshcontroller.py
I'll test this evening if nobody beats me to it in the next hour or so.
Fixes: #38
=> Combine stderr into stdout

robotpy_installer/installer.py, tests/sample-requirements.txt, tests/test_basic.py
Also re-enable the tests, avoiding the chicken-and-egg problem.
=> Fix `download -r requirements.txt`

robotpy_installer/cacheserver.py, robotpy_installer/robotfinder.py, robotpy_installer/sshcontroller.py, robotpy_installer/utils.py
- Fixes #64
- Maybe https://github.com/robotpy/pyfrc/issues/204 too? 
@TheTripleV any chance you can try this out on Windows?
=> More efficient finding

robotpy_installer/installer.py
https://github.com/wpilibsuite/BetaTest/releases/tag/ni-beta-release-3
wpilibsuite/GradleRIO#634
=> Bump roboRIO image for WPILib 2023.1.1-beta-7

robotpy_installer/_pipstub.py, robotpy_installer/installer.py, robotpy_installer/opkgrepo.py, robotpy_installer/robotfinder.py, robotpy_installer/sshcontroller.py, robotpy_installer/utils.py, tests/run_tests.py
- socket.getaddrinfo has different behavior on Windows vs macOS/Linux
@martinrioux please try this and let me know if this fixes your issue
=> Fix _resolve_addr on windows

.github/workflows/dist.yml, robotpy_installer/deploy.py, robotpy_installer/deploy_info.py, robotpy_installer/installer.py, robotpy_installer/sshcontroller.py, robotpy_installer/undeploy.py, robotpy_installer/utils.py, setup.cfg
https://github.com/robotpy/pyfrc/pull/226
=> Add deploy utilities to robotpy-installer

robotpy_installer/cli_deploy.py, robotpy_installer/cli_init.py, robotpy_installer/pyproject.py, setup.cfg
- deploy once again verifies the local installation
- Add list of extras to the default generated pyproject.toml
- Add `robotpy init` command
=> Various pyproject.toml related improvements

robotpy_installer/cli_installer.py, robotpy_installer/installer.py
=> Allow using requirements.txt again

MANIFEST.in, robotpy_installer/cli_deploy.py, robotpy_installer/frcKillRobot.sh, robotpy_installer/roborio_utils.py
- From https://github.com/wpilibsuite/GradleRIO/pull/699
- Fixes #111
=> Add updated frcKillRobot.sh script to ensure robot code dies

robotpy_installer/cli_installer.py
=> Add simple SSH command for diagnostic purposes

robotpy_installer/roborio_utils.py
=> Ensure frcKillRobot.sh is always using unix newlines

robotpy_installer/cli_deploy.py
=> Kill the robot before copying files

robotpy_installer/installer.py
=> Fix reported memory usage

robotpy_installer/cli_sync.py, robotpy_installer/pyproject.py
- This is mostly cosmetic, but hopefully communicates the purpose better
- Fixes #118
=> Replace 'robotpy_extras' with 'components'
